import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  fund: [
    {
      type: 'autogenerated',
      dirName: 'fund',
    },
  ],
  bank: [
    {
      type: 'autogenerated',
      dirName: 'bank',
    },
  ],
  securities: [
    {
      type: 'autogenerated',
      dirName: 'securities',
    },
  ],
};

export default sidebars;
