/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "金融解决方案知识库",
  "tagline": "基金 · 银行 · 证券 业务场景深度拆解",
  "favicon": "img/favicon.ico",
  "url": "https://your-site.vercel.app",
  "baseUrl": "/",
  "projectName": "fin-knowledge",
  "organizationName": "your-name",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "zh-Hans",
    "locales": [
      "zh-Hans"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/your-name/fin-knowledge/edit/main/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/social-card.jpg",
    "navbar": {
      "title": "金融知识库",
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "fund",
          "position": "left",
          "label": "基金"
        },
        {
          "type": "docSidebar",
          "sidebarId": "bank",
          "position": "left",
          "label": "银行"
        },
        {
          "type": "docSidebar",
          "sidebarId": "securities",
          "position": "left",
          "label": "证券"
        },
        {
          "to": "/documents",
          "position": "left",
          "label": "文档库"
        },
        {
          "to": "/upload",
          "position": "left",
          "label": "上传文档"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "copyright": "Copyright © 2026 金融解决方案知识库",
      "links": []
    },
    "prismTheme": {
      "plain": {
        "color": "#393A34",
        "backgroundColor": "#f6f8fa"
      },
      "styles": [
        {
          "types": [
            "comment",
            "prolog",
            "doctype",
            "cdata"
          ],
          "style": {
            "color": "#999988",
            "fontStyle": "italic"
          }
        },
        {
          "types": [
            "namespace"
          ],
          "style": {
            "opacity": 0.7
          }
        },
        {
          "types": [
            "string",
            "attr-value"
          ],
          "style": {
            "color": "#e3116c"
          }
        },
        {
          "types": [
            "punctuation",
            "operator"
          ],
          "style": {
            "color": "#393A34"
          }
        },
        {
          "types": [
            "entity",
            "url",
            "symbol",
            "number",
            "boolean",
            "variable",
            "constant",
            "property",
            "regex",
            "inserted"
          ],
          "style": {
            "color": "#36acaa"
          }
        },
        {
          "types": [
            "atrule",
            "keyword",
            "attr-name",
            "selector"
          ],
          "style": {
            "color": "#00a4db"
          }
        },
        {
          "types": [
            "function",
            "deleted",
            "tag"
          ],
          "style": {
            "color": "#d73a49"
          }
        },
        {
          "types": [
            "function-variable"
          ],
          "style": {
            "color": "#6f42c1"
          }
        },
        {
          "types": [
            "tag",
            "selector",
            "keyword"
          ],
          "style": {
            "color": "#00009f"
          }
        }
      ]
    },
    "prismDarkTheme": {
      "plain": {
        "color": "#9CDCFE",
        "backgroundColor": "#1E1E1E"
      },
      "styles": [
        {
          "types": [
            "prolog"
          ],
          "style": {
            "color": "rgb(0, 0, 128)"
          }
        },
        {
          "types": [
            "comment"
          ],
          "style": {
            "color": "rgb(106, 153, 85)"
          }
        },
        {
          "types": [
            "builtin",
            "changed",
            "keyword",
            "interpolation-punctuation"
          ],
          "style": {
            "color": "rgb(86, 156, 214)"
          }
        },
        {
          "types": [
            "number",
            "inserted"
          ],
          "style": {
            "color": "rgb(181, 206, 168)"
          }
        },
        {
          "types": [
            "constant"
          ],
          "style": {
            "color": "rgb(100, 102, 149)"
          }
        },
        {
          "types": [
            "attr-name",
            "variable"
          ],
          "style": {
            "color": "rgb(156, 220, 254)"
          }
        },
        {
          "types": [
            "deleted",
            "string",
            "attr-value",
            "template-punctuation"
          ],
          "style": {
            "color": "rgb(206, 145, 120)"
          }
        },
        {
          "types": [
            "selector"
          ],
          "style": {
            "color": "rgb(215, 186, 125)"
          }
        },
        {
          "types": [
            "tag"
          ],
          "style": {
            "color": "rgb(78, 201, 176)"
          }
        },
        {
          "types": [
            "tag"
          ],
          "languages": [
            "markup"
          ],
          "style": {
            "color": "rgb(86, 156, 214)"
          }
        },
        {
          "types": [
            "punctuation",
            "operator"
          ],
          "style": {
            "color": "rgb(212, 212, 212)"
          }
        },
        {
          "types": [
            "punctuation"
          ],
          "languages": [
            "markup"
          ],
          "style": {
            "color": "#808080"
          }
        },
        {
          "types": [
            "function"
          ],
          "style": {
            "color": "rgb(220, 220, 170)"
          }
        },
        {
          "types": [
            "class-name"
          ],
          "style": {
            "color": "rgb(78, 201, 176)"
          }
        },
        {
          "types": [
            "char"
          ],
          "style": {
            "color": "rgb(209, 105, 105)"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
